services:
  backend:
    build: 
      context: ./backend/RealTime-CodeSync
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/CodeSync
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend/realtime-collabrative-editor
      dockerfile: Dockerfile
      args:
        - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL:-https://devbridgeide.onrender.com}
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=CodeSync
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
